export default {
  data: [
  {
    id: 0,
    name: 'name',
    title: 'Имя',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 1,
    name: 'surname',
    title: 'Фаммилия',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 2,
    name: 'fatherName',
    title: 'Отчество',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 3,
    name: 'age',
    title: 'Возраст',
    isSorted: false,
    width: 'mid',
  },
  {
    id: 4,
    name: 'birthday',
    title: 'Дата рождения',
    isSorted: false,
    width: 'mid',
  },
  {
    id: 5,
    name: 'ampluaVariations',
    title: 'Игровые амплуа',
    isSorted: false,
    width: 'mid',
  },
   {
    id: 6,
    name: 'totalGamesInCarear',
    title: 'Сыгранные матчи (в карьере)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 7,
    name: 'totalGamesInSeason',
    title: 'Сыгранные матчи (в сезоне)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 8,
    name: 'totalGoalScoredInCarear',
    title: 'Голы забитые (в карьере)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 9,
    name: 'totalGoalConsendedInCarear',
    title: 'Голы пропущенные (в карьере)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 10,
    name: 'totalGameInInCarear',
    title: 'Выходов на замену (в карьере)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 11,
    name: 'totalGameOutInCarear',
    title: 'Был заменён (в карьере)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 12,
    name: 'totalGoalScoredInSeason',
    title: 'Голы забитые (в сезоне)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 13,
    name: 'totalGoalConsendedInSeason',
    title: 'Голы пропущенные (в сезоне)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 14,
    name: 'totalGameInInSeason',
    title: 'Выходов на замену (в сезоне)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 15,
    name: 'totalGameOutInSeason',
    title: 'Был заменён (в сезоне)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 16,
    name: 'totalAsistsInCarear',
    title: 'Голевые передачи (в карьере)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 17,
    name: 'totalAsistsInSeason',
    title: 'Голевые передачи (в сезоне)',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 18,
    name: 'lastMatch',
    title: 'Последний выход на поле',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 19,
    name: 'notes',
    title: 'Заметки',
    isSorted: false,
    width: 'large',
  },
  {
    id: 20,
    name: 'trainingPayType',
    title: 'Вид оплаты тренировок',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 21,
    name: 'debtors',
    title: 'Задолжности',
    isSorted: false,
    width: 'upper-mid',
  },
  {
    id: 22,
    name: 'id',
    title: 'АйДи в базе',
    isSorted: false,
    width: 'mid',
  },
  {
    id: 23,
    name: 'weight',
    title: 'Вес',
    isSorted: false,
    width: 'mid',
  },
  {
    id: 24,
    name: 'height',
    title: 'Рост',
    isSorted: false,
    width: 'mid',
  },
  ]
}