export default {
  data: [
    {
      id: 0,
      name: 'Сергей',
      surname: 'Попов',
      fatherName: 'Сергеевич ',
      birthday:  new Date('2002-10-06'),
      weight: null,
      height: null,
    },
    {
      id: 1,
      name: 'Дмитрий',
      surname: 'Данилов',
      fatherName: 'Валерьевич',
      birthday:  new Date('1995-05-13'),
      weight: null,
      height: null,
    },
    {
      id: 2,
      name: 'Антон',
      surname: 'Ивашев',
      fatherName: null,
      birthday:  null,
      weight: null,
      height: null,
    },
    {
      id: 3,
      name: 'Арман',
      surname: 'Элоян',
      fatherName: 'Степанович',
      birthday:  null,
      weight: null,
      height: null,
    },
    {
      id: 4,
      name: 'Сергей',
      surname: 'Моисеев',
      fatherName: 'Сергеевич',
      birthday:  new Date('1995-06-10'),
      weight: null,
      height: null,
    },
    {
      id: 12,
      name: 'Дмитрий',
      surname: 'Золотарёв',
      fatherName: 'Владимирович',
      birthday:  new Date('1999-03-10'),
      weight: null,
      height: null,
    },
    {
      id: 5,
      name: 'Александр',
      surname: 'Галухин',
      fatherName: 'Александрович',
      birthday:  new Date('1987-11-30'),
      weight: null,
      height: null,
    },
    {
      id: 6,
      surname: 'Яценко',
      name: 'Денис',
      fatherName: 'Александрович',
      birthday:  new Date('1994-04-01'),
      weight: null,
      height: null,
    },
    {
      id: 7,
      surname: 'Колядко',
      name: 'Владислав',
      fatherName: 'Владимирович',
      birthday:  new Date('1991-05-07'),
      weight: null,
      height: null,
    },
    {
      id: 8,
      surname: 'Гребенник',
      name: 'Данила',
      fatherName: 'Юрьевич',
      birthday:  new Date('1996-09-11'),
      weight: null,
      height: null,
    },
    {
      id: 9,
      surname: 'Лесной',
      name: 'Александр',
      fatherName: 'Владимирович',
      birthday:  new Date('1991-09-06'),
      weight: null,
      height: null,
    },
    {
      id: 10,
      surname: 'Иванов',
      name: 'Вячеслав',
      fatherName: 'Анатольевич',
      birthday:  null,
      weight: null,
      height: null,
    },
    {
      id: 11,
      surname: 'Яковлев',
      name: 'Станислав',
      fatherName: 'Александрович',
      birthday:  new Date('1995-07-13'),
      weight: null,
      height: null,
    },
  ],
}