export default {
  data: [
    {
      id: 0,
      playerId: 0,
      totalGamesInSeason: 16,
      totalGoalConsendedInSeason: 12,
      totalGameOutInSeason: 1,
    },
    {
      id: 1,
      playerId: 1,
      totalGamesInSeason: 12,
      totalGoalConsendedInSeason: 10,
      totalGameOutInSeason: 1,
    },
    {
      id: 2,
      playerId: 2,
      totalGamesInSeason: 14,
      totalGoalConsendedInSeason: 12,
      totalGameOutInSeason: 2,
    },
    {
      id: 3,
      playerId: 3,
      totalGamesInSeason: 32,
      totalGameOutInSeason: 6,
      totalGameInInSeason: 8,
      totalAsistsInSeason: 2,
      totalGoalScoredInSeason: 6,
    },
    {
      id: 4,
      playerId: 4,
      totalGamesInSeason: 16,
      totalGameOutInSeason: 1,
      totalGameInInSeason: 1,
    },
    {
      id: 5,
      playerId: 12,
      totalGamesInSeason: 20,
      totalGameInInSeason: 1,
    },
    {
      id: 6,
      playerId: 5,
      totalGamesInSeason: 10,
      totalGameOutInSeason: 2,
      totalGameInInSeason: 3,
    },
    {
      id: 7,
      playerId: 6,
      totalGamesInSeason: 14,
      totalAsistsInSeason: 2,
    },
    {
      id: 8,
      playerId: 7,
      totalGamesInSeason: 12,
      totalGameOutInSeason: 2,
      totalGameInInSeason: 3,
    },
    {
      id: 9,
      playerId: 8,
      totalGamesInSeason: 15,
      totalGameOutInSeason: 2,
      totalGameInInSeason: 4,
      totalAsistsInSeason: 6,
      totalGoalScoredInSeason: 4,
    },
    {
      id: 10,
      playerId: 9,
      totalGamesInSeason: 33,
      totalGameOutInSeason: 2,
      totalGameInInSeason: 1,
      totalAsistsInSeason: 16,
      totalGoalScoredInSeason: 10,
    },
    {
      id: 11,
      playerId: 10,
      totalGamesInSeason: 26,
      totalGameOutInSeason: 1,
      totalAsistsInSeason: 20,
      totalGoalScoredInSeason: 12,
    },
    {
      id: 12,
      playerId: 11,
      totalGamesInSeason: 20,
      totalGameInInSeason: 1,
      totalGameOutInSeason: 2,
      totalAsistsInSeason: 14,
      totalGoalScoredInSeason: 8,
    },
  ],
}